# SETLIST CONSTRAINTS
SETLIST_API_KEY = 'SETLIST_API_KEY'
SETLIST_BASE_URL = 'SETLIST_BASE_URL'

# SPOTIFY CONSTRAINTS
SPOTIFY_CLIENT_ID = 'SPOTIFY_CLIENT_ID'
SPOTIFY_SECRET_ID = 'SPOTIFY_SECRET_ID'
SPOTIFY_REDIRECT_URI = 'SPOTIFY_REDIRECT_URI'
